# -*- coding: utf-8 -*-
"""Diagram.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qM_FXcuWaonvGWIkKFdhOiHYmJEQmJz2
"""

pip install diagrams

from urllib.request import urlretrieve

from diagrams import Cluster, Diagram
from diagrams.aws.database import Aurora
from diagrams.custom import Custom
from diagrams.k8s.compute import Pod
from diagrams.aws.storage import S3
from diagrams.aws.compute import Lambda
from diagrams.aws.database import Dynamodb

# Download an image to be used into a Custom Node class
csv_url = "https://www.iconpacks.net/icons/2/free-csv-icon-1518-thumb.png"
csv_icon = "csv.png"

lambda_url = "https://codeahoy.com/assets/images/compare/python-frameworks/fastapi-logo.png"
lambda_icon = "fastapi-logo.png"

octa_url = "https://symbols-electrical.getvecta.com/stencil_90/12_okta-icon"
octa_icon = "octa.png"

user_url = "https://cahtc.com/wp-content/uploads/2016/11/user-icon.png"
user_icon = "user-icon.png"


with Diagram("DAS Architecture", show=False):
    
    queue = Custom("Data", csv_icon) 
    queue1 = Custom("API", lambda_icon)
    queue2 = Custom("User", user_icon)
    queue3 = Custom("Sign-in", octa_icon)

    queue >> S3("staging") >> Lambda("function") >> Dynamodb("storage") >> queue1 >> queue3 >> queue2